/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Link = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'desc' : IDL.Text,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLinkWithPin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getAllLinks' : IDL.Func([], [IDL.Vec(Link)], []),
  'getDefaultLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
  'removeLinkWithPin' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Link = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'desc' : IDL.Text,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  
  return IDL.Service({
    'addLinkWithPin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getAllLinks' : IDL.Func([], [IDL.Vec(Link)], []),
    'getDefaultLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
    'removeLinkWithPin' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };